### ISSUE TITLE
feat: 项目还有继续维护的想法么，加一个预览怎么样

### ISSUE THREAD

**Issue by wangerzi** [Riunshow/gin-vue-admin_RE#1]
很赞👍，我选 gin-vue-admin 的时候也在想前端选型和实现还可以更好一点；

不过这个项目没有预览界面，可能看的人会少些，毕竟纯前端项目，可以直接部署在 OSS 上，有需要的话可以放我这边，我买过 CDN 套餐可以承载项目预览的消耗。

**Comment by Riunshow** [comment]
前段日子工作压力暂时有些大, 不过这些日子会捡起来继续写 =.=

不过在考虑是否接入gin-vue-admin的服务端 还是纯做前端的展示

**Comment by wangerzi** [comment]
我最近事情也不少，没什么时间投入到开源里边来，我觉着预览打包的时候开启 mock 模拟数据即可，页面上渲染一下提示信息说明这是纯前端项目，对接 gin-vue-admin 后端以及 mock 的使用整个文档就挺好的。

**Comment by Riunshow** [comment]
你的这个建议很不错,  有兴趣来一起维护嘛~~~

**Comment by wangerzi** [comment]
来啊，搞事情，我的话四月中旬前后预计有时间，我中间熟悉下代码😁

**Comment by Riunshow** [comment]
阔以, 终于不是一个人了
